version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      prod:
        dependency-type: production
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
      dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps): "
