# WARNING: do not edit this file, it's automatically generated by `npm run l10n`.
# If you need to manually add strings, do so in ./locales/en-US.ftl. See ./README.md for more details.

article-footer-last-modified = This page was last modified on <time data-l10n-name="date">{ $date }</time> by <a data-l10n-name="contributors">MDN contributors</a>.
article-footer-source-title = Folder: { $folder } (Opens in a new tab)
baseline-asterisk = Some parts of this feature may have varying levels of support.
baseline-high-extra = This feature is well established and works across many devices and browser versions. It’s been available across browsers since { $date }.
baseline-low-extra = Since { $date }, this feature works across the latest devices and browser versions. This feature might not work in older devices or browsers.
baseline-not-extra = This feature is not Baseline because it does not work in some of the most widely-used browsers.
baseline-supported-in = Supported in { $browsers }
baseline-unsupported-in = Not widely supported in { $browsers }
baseline-supported-and-unsupported-in = Supported in { $supported }, but not widely supported in { $unsupported }
homepage-hero-title = Resources for Developers,<br> by Developers
homepage-hero-description = Documenting <a data-l10n-name="css">CSS</a>, <a data-l10n-name="html">HTML</a>, and <a data-l10n-name="js">JavaScript</a>, since 2005.
not-found-title = Page not found
not-found-description = Sorry, the page <code data-l10n-name="url">{ $url }</code> could not be found.
not-found-fallback-english = <strong data-l10n-name="strong">Good news:</strong> The page you requested exists in <em data-l10n-name="em">English</em>.
not-found-fallback-search = The page you requested doesn't exist, but you could try a site search for:
not-found-back = Go back to the home page
footer-mofo = Visit <a data-l10n-name="moco">Mozilla Corporation’s</a> not-for-profit parent, the <a data-l10n-name="mofo">Mozilla Foundation</a>.
footer-copyright = Portions of this content are ©1998–{ $year } by individual mozilla.org contributors. Content available under <a data-l10n-name="cc">a Creative Commons license</a>.
search-modal-site-search = Site search for <em>{ $query }</em>
site-search-search-stats = Found { $results } documents.
site-search-suggestion-matches =
    { $relation ->
        [gt]
            more than { $matches ->
                [one] { $matches } match
               *[other] { $matches } matches
            }
       *[eq]
            { $matches ->
                [one] { $matches } match
               *[other] { $matches } matches
            }
    }
blog-time-to-read =
    { $minutes ->
        [one] { $minutes } minute read
       *[other] { $minutes } minutes read
    }
-brand-name-obs = HTTP Observatory
obs-report = Report
obs-title = { -brand-name-obs }
obs-landing-intro = Launched in 2016, the { -brand-name-obs } enhances web security by analyzing compliance with best security practices. It has provided insights to over 6.9 million websites through 47 million scans.
obs-assessment = Developed by Mozilla, the { -brand-name-obs } performs an in-depth assessment of a site’s HTTP headers and other key security configurations.
obs-scanning = Its automated scanning process provides developers and website administrators with detailed, actionable feedback, focusing on identifying and addressing potential security vulnerabilities.
obs-security = The tool is instrumental in helping developers and website administrators strengthen their sites against common security threats in a constantly advancing digital environment.
obs-mdn = The { -brand-name-obs } provides effective security insights, guided by Mozilla's expertise and commitment to a safer and more secure internet and based on well-established trends and guidelines.
compat-browser-version-date = { $browser } { $version } – Release date: { $date }
compat-browser-version-released = Release date: { $date }
compat-link-source-title = File: { $filename }
compat-support-prefix = Implemented with the vendor prefix: { $prefix }
compat-support-altname = Alternate name: { $altname }
compat-support-removed = Removed in { $version } and later
compat-support-see-impl-url = See <a data-l10n-name="impl_url">{ $label }</a>
compat-support-flags =
    { NUMBER($has_added) ->
        [one] From version { $version_added }
       *[other] { "" }
    }{ $has_last ->
        [one]
            { NUMBER($has_added) ->
               *[zero] Until { $versionLast } users
                [one] { " " }until { $versionLast } users
            }
       *[zero]
            { NUMBER($has_added) ->
               *[zero] Users
                [one] { " " }users
            }
    }
    { " " }must explicitly set the <code data-l10n-name="name">{ $flag_name }</code>{ " " }
    { $flag_type ->
       *[preference] preference
        [runtime_flag] runtime flag
    }{ NUMBER($has_value) ->
        [one] { " " }to <code data-l10n-name="value">{ $flag_value }</code>
       *[other] { "" }
    }{ "." }
    { NUMBER($has_pref_url) ->
        [one]
            { $flag_type ->
                [preference] To change preferences in { $browser_name }, visit { $browser_pref_url }.
               *[other] { "" }
            }
       *[other] { "" }
    }
compat-legend-yes = { compat-support-full }
compat-legend-partial = { compat-support-partial }
compat-legend-preview = In development. Supported in a pre-release version.
compat-legend-no = { compat-support-no }
compat-legend-unknown = Compatibility unknown
compat-legend-experimental = { compat-experimental }. Expect behavior to change in the future.
compat-legend-nonstandard = { compat-nonstandard }. Check cross-browser support before using.
compat-legend-deprecated = { compat-deprecated }. Not for use in new websites.
compat-legend-footnote = See implementation notes.
compat-legend-disabled = User must explicitly enable this feature.
compat-legend-altname = Uses a non-standard name.
compat-legend-prefix = Requires a vendor prefix or different name for use.
compat-legend-more = Has more compatibility info.
placement-note = Ad
placement-no = Don't want to see ads?
pagination-next = Next page
pagination-prev = Previous page
pagination-current = Current page
pagination-goto = Go to page { $page }
logout = Sign out
login = Log in
example-play-button-label = Play
example-play-button-title = Run example in MDN Playground (opens in new tab)
writer-reload-polling = Polling every { $seconds }s
a11y-menu-skip-to-main-content = Skip to main content
a11y-menu-skip-to-search = Skip to search
article-footer-title = Help improve MDN
article-footer-learn-how-to-contribute = Learn how to contribute
article-footer-view-this-page-on-github = View this page on GitHub
article-footer-this-will-take-you-to-github-to = This will take you to GitHub to file a new issue.
article-footer-report-a-problem-with-this-conte = Report a problem with this content
baseline-indicator-baseline-cross = Baseline Cross
baseline-indicator-baseline-check = Baseline Check
baseline-indicator-limited-availability = Limited availability
baseline-indicator-baseline = Baseline
baseline-indicator-widely-available = Widely available
baseline-indicator-newly-available = Newly available
baseline-indicator-check = check
baseline-indicator-cross = cross
baseline-indicator-learn-more = Learn more
baseline-indicator-see-full-compatibility = See full compatibility
baseline-indicator-report-feedback = Report feedback
blog-previous = Previous post
blog-next = Next post
blog-index-blog-it-better = Blog it better
reference-toc-header = In this article
blog-post-not-found = Blog post not found.
collection-save-button-save-in-collection = Save in collection
collection-save-button-remove = Remove
collection-save-button-save = Save
collection-save-button-add-to-collection = Add to collection
collection-save-button-collection = Collection:
collection-save-button-saved-articles = Saved articles
collection-save-button-new-collection = New collection
collection-save-button-name = Name:
collection-save-button-note = Note:
collection-save-button-saving = Saving…
collection-save-button-cancel = Cancel
collection-save-button-deleting = Deleting…
collection-save-button-delete = Delete
theme-default = OS default
color-theme-light = Light
color-theme-dark = Dark
color-theme-switch-color-theme = Switch color theme
color-theme-theme = Theme
compat-link-report-issue-title = Report an issue with this compatibility data
compat-link-report-issue = Report problems with this compatibility data
compat-link-source = View data on GitHub
compat-experimental = Experimental
compat-deprecated = Deprecated
compat-nonstandard = Non-standard
compat-support-partial = Partial support
compat-support-preview-browser = Preview browser support
compat-support-full = Full support
compat-support-no = No support
compat-support-unknown = Support unknown
compat-yes = Yes
compat-partial = Partial
compat-no = No
compat-support-preview = Preview support
compat-legend = Legend
compat-legend-tip = Tip: you can click/tap on a cell for more information.
compat-link-report-missing-title = Report missing compatibility data
compat-link-report-missing = Report this issue
compat-js-required = Enable JavaScript to view this browser compatibility table.
compat-loading = Loading…
content-feedback-content-is-out-of-date = Content is out of date
content-feedback-missing-information = Missing information
content-feedback-code-examples-not-working-as-exp = Code examples not working as expected
content-feedback-other = Other
content-feedback-question = Was this page helpful to you?
content-feedback-yes = Yes
content-feedback-no = No
content-feedback-reason = Why was this page not helpful to you?
content-feedback-submit = Submit
content-feedback-thanks = Thank you for your feedback!
contributor-spotlight-want-to-be-part-of-the-journey = Want to be part of the journey?
contributor-spotlight-our-constant-quest-for-innovatio = Our constant quest for innovation starts here, with you. Every part of MDN (docs, demos and the site itself) springs from our incredible open community of developers. Please join us!
contributor-spotlight-get-involved = Get involved
contributor-spotlight-contributor-profile = Contributor profile
copy-button-copied = Copied
copy-button-copy-failed = Copy failed!
copy-button-copy = Copy
footer-mdn-on-github = MDN on GitHub
footer-mdn-on-bluesky = MDN on Bluesky
footer-mdn-on-x = MDN on X
footer-mdn-on-mastodon = MDN on Mastodon
footer-mdn-blog-rss-feed = MDN blog RSS feed
footer-mdn = MDN
footer-about = About
footer-blog = Blog
footer-mozilla-careers = Mozilla careers
footer-advertise-with-us = Advertise with us
footer-mdn-plus = MDN Plus
footer-product-help = Product help
footer-contribute = Contribute
footer-mdn-community = MDN Community
footer-community-resources = Community resources
footer-writing-guidelines = Writing guidelines
footer-mdn-discord = MDN Discord
footer-developers = Developers
footer-web-technologies = Web technologies
footer-learn-web-development = Learn web development
footer-guides = Guides
footer-tutorials = Tutorials
footer-glossary = Glossary
footer-hacks-blog = Hacks blog
footer-website-privacy-notice = Website Privacy Notice
footer-telemetry-settings = Telemetry Settings
footer-legal = Legal
footer-community-participation-guidelin = Community Participation Guidelines
footer-mdn-logo = MDN logo
footer-tagline = Your blueprint for a better internet.
footer-mozilla-logo = Mozilla logo
generic-toc__header = In this article
homepage-body-featured-articles = Featured articles
homepage-body-latest-news = Latest news
homepage-body-recent-contributions = Recent contributions
homepage-contributor-spotlight-contributor-spotlight = Contributor Spotlight
homepage-contributor-spotlight-get-involved = Get involved
homepage-search-search-the-site = Search the site
homepage-search-search = Search
interactive-example-reset = Reset
interactive-example-value-select = Value select
interactive-example-the-current-value-is-not-support = The current value is not supported by your browser.
interactive-example-run-example-and-show-console-ou = Run example, and show console output
interactive-example-run = Run
interactive-example-reset-example-and-clear-console = Reset example, and clear console output
interactive-example-console-output = Console output
interactive-example-output = Output
issues-table-loading-issues = loading issues…
issues-table-title = Title
issues-table-repository = Repository
language-switcher-remember-language = Remember language
language-switcher-enable-this-setting-to-always-sw = Enable this setting to always switch to the current language when available. (Click to learn more.)
language-switcher-learn-more = Learn more
login-button-login = Login
modal-exit-modal = Exit modal
navigation-toggle-navigation = Toggle navigation
obs-about-title = About the HTTP Observatory
observatory-landing-read-our-faq = Read our FAQ
observatory-landing-report-feedback = Report Feedback
observatory-rescan-button-rescan = Rescan
observatory-rescan-button-wait-a-minute-to-rescan = Wait a minute to rescan
observatory-results-report-feedback = Report Feedback
observatory-results-faq = FAQ
observatory-tests-and-scores-loading-tests-and-scoring-data = Loading tests and scoring data...
observatory-tests-and-scores-see = See
observatory-tests-and-scores-for-guidance = for guidance.
observatory-tests-and-scores-test-result = Test result
observatory-tests-and-scores-description = Description
observatory-tests-and-scores-modifier = Modifier
observatory-tests-and-scores-failed-to-load-tests-and-scoring = Failed to load tests and scoring data. Please try again later.
brand-web-docs = MDN Web Docs
blog-rss-title = MDN Blog RSS Feed
meta-description = The MDN Web Docs site provides information about Open Web technologies including HTML, CSS, and APIs for both Web sites and progressive web apps.
logo-alt = The MDN logo
pagination-pagination = Pagination
playground-do-you-really-want-to-clear-ever = Do you really want to clear everything?
playground-do-you-really-want-to-revert-you = Do you really want to revert your changes?
playground-playground = Playground
playground-format = Format
playground-run = Run
playground-share = Share
playground-clear = Clear
playground-reset = Reset
playground-seeing-something-inappropriate = Seeing something inappropriate?
playground-console = Console
playground-share-markdown = Share Markdown
playground-copy-markdown-to-clipboard = Copy markdown to clipboard
playground-share-data-url = Share Data URL
playground-copy-data-url-to-clipboard = Copy data URL to clipboard
playground-share-your-code-via-permalink = Share your code via Permalink
playground-copy-to-clipboard = Copy to clipboard
playground-create-link = Create link
playground-report-this-malicious-or-inappro = Report this malicious or inappropriate shared playground.
playground-can-you-please-share-some-detail = Can you please share some details on what's wrong with this content:
playground-cancel = Cancel
playground-report = Report
recently-visited-recently-visited = Recently visited
scrim-inline-clicking-will-load-content-from = Clicking will load content from scrimba.com
scrim-inline-toggle-fullscreen = Toggle fullscreen
scrim-inline-open-on-scrimba = Open on Scrimba
scrim-inline-load-scrim-and-open-dialog = Load scrim and open dialog.
search-button-search-the-site = Search the site
search-modal-loading-search-index = Loading search index…
search-modal-search = Search
search-modal-exit-search = Exit search
sidebar-filter-filter-sidebar = Filter sidebar
sidebar-filter-filter = Filter
sidebar-filter-clear-filter-input = Clear filter input
site-search-search = Search
site-search-previous = Previous
site-search-next = Next
site-search-suggestions-text = Did you mean…
site-search-searching = Searching…
site-search-language = Language
site-search-both = Both
specifications-list-this-feature-does-not-appear-to = This feature does not appear to be defined in any specification.
specifications-list-specification = Specification
survey-hide-this-survey = Hide this survey
survey-take-survey-opens-in-a-new-tab = Take survey (Opens in a new tab)
toggle-sidebar-toggle-sidebar = Toggle sidebar
user-menu-ai-help = AI Help
user-menu-collections = Collections
user-menu-updates = Updates
user-menu-settings = My settings
user-menu-help = Help
user-menu-feedback = Feedback
user-menu-user = User
writer-open-editor-open-in-editor = Open in editor
writer-toolbar-view-on-mdn = View on MDN
menu-html = HTML
menu-html-panel-title = HTML: Markup language
menu-html-html-reference = HTML reference
menu-html-html-reference-elements = Elements
menu-html-html-reference-global-attributes = Global attributes
menu-html-html-reference-attributes = Attributes
menu-html-html-reference-see-all = See all…
menu-html-html-reference-see-all-label = See all HTML references
menu-html-html-guides = HTML guides
menu-html-html-guides-responsive-images = Responsive images
menu-html-html-guides-html-cheatsheet = HTML cheatsheet
menu-html-html-guides-date-time-formats = Date & time formats
menu-html-html-guides-see-all = See all…
menu-html-html-guides-see-all-label = See all HTML guides
menu-html-markup-languages = Markup languages
menu-html-markup-languages-svg = SVG
menu-html-markup-languages-mathml = MathML
menu-html-markup-languages-xml = XML
menu-css = CSS
menu-css-panel-title = CSS: Styling language
menu-css-css-reference = CSS reference
menu-css-css-reference-properties = Properties
menu-css-css-reference-selectors = Selectors
menu-css-css-reference-at-rules = At-rules
menu-css-css-reference-values = Values
menu-css-css-reference-see-all = See all…
menu-css-css-reference-see-all-label = See all CSS references
menu-css-css-guides = CSS guides
menu-css-css-guides-box-model = Box model
menu-css-css-guides-animations = Animations
menu-css-css-guides-flexbox = Flexbox
menu-css-css-guides-colors = Colors
menu-css-css-guides-see-all = See all…
menu-css-css-guides-see-all-label = See all CSS guides
menu-css-layout-cookbook = Layout cookbook
menu-css-layout-cookbook-column-layouts = Column layouts
menu-css-layout-cookbook-centering-an-element = Centering an element
menu-css-layout-cookbook-card-component = Card component
menu-css-layout-cookbook-see-all = See all…
menu-javascript = JavaScript
menu-javascript-short = JS
menu-javascript-panel-title = JavaScript: Scripting language
menu-javascript-js-reference = JS reference
menu-javascript-js-reference-standard-built-in-objects = Standard built-in objects
menu-javascript-js-reference-expressions-operators = Expressions & operators
menu-javascript-js-reference-statements-declarations = Statements & declarations
menu-javascript-js-reference-functions = Functions
menu-javascript-js-reference-see-all = See all…
menu-javascript-js-reference-see-all-label = See all JavaScript references
menu-javascript-js-guides = JS guides
menu-javascript-js-guides-control-flow-error-handing = Control flow & error handing
menu-javascript-js-guides-loops-and-iteration = Loops and iteration
menu-javascript-js-guides-working-with-objects = Working with objects
menu-javascript-js-guides-using-classes = Using classes
menu-javascript-js-guides-see-all = See all…
menu-javascript-js-guides-see-all-label = See all JavaScript guides
menu-webapis = Web APIs
menu-webapis-panel-title = Web APIs: Programming interfaces
menu-webapis-web-api-reference = Web API reference
menu-webapis-web-api-reference-file-system-api = File system API
menu-webapis-web-api-reference-fetch-api = Fetch API
menu-webapis-web-api-reference-geolocation-api = Geolocation API
menu-webapis-web-api-reference-html-dom-api = HTML DOM API
menu-webapis-web-api-reference-push-api = Push API
menu-webapis-web-api-reference-service-worker-api = Service worker API
menu-webapis-web-api-reference-see-all = See all…
menu-webapis-web-api-reference-see-all-label = See all Web API guides
menu-webapis-web-api-guides = Web API guides
menu-webapis-web-api-guides-using-the-web-animation-api = Using the Web animation API
menu-webapis-web-api-guides-using-the-fetch-api = Using the Fetch API
menu-webapis-web-api-guides-working-with-the-history-api = Working with the History API
menu-webapis-web-api-guides-using-the-web-speech-api = Using the Web speech API
menu-webapis-web-api-guides-using-web-workers = Using web workers
menu-all = All
menu-all-panel-title = All web technology
menu-all-technologies = Technologies
menu-all-technologies-accessibility = Accessibility
menu-all-technologies-http = HTTP
menu-all-technologies-uri = URI
menu-all-technologies-web-extensions = Web extensions
menu-all-technologies-webassembly = WebAssembly
menu-all-technologies-webdriver = WebDriver
menu-all-technologies-see-all = See all…
menu-all-technologies-see-all-label = See all web technology references
menu-all-topics = Topics
menu-all-topics-media = Media
menu-all-topics-performance = Performance
menu-all-topics-privacy = Privacy
menu-all-topics-security = Security
menu-all-topics-progressive-web-apps = Progressive web apps
menu-learn = Learn
menu-learn-panel-title = Learn web development
menu-learn-frontend-developer-course = Frontend developer course
menu-learn-frontend-developer-course-getting-started-modules = Getting started modules
menu-learn-frontend-developer-course-core-modules = Core modules
menu-learn-frontend-developer-course-mdn-curriculum = MDN Curriculum
menu-learn-frontend-developer-course-check-out-the-video-course-from-scrimba-our-partner = Check out the video course from Scrimba, our partner
menu-learn-learn-html = Learn HTML
menu-learn-learn-html-structuring-content-with-html-module = Structuring content with HTML module
menu-learn-learn-css = Learn CSS
menu-learn-learn-css-css-styling-basics-module = CSS styling basics module
menu-learn-learn-css-css-layout-module = CSS layout module
menu-learn-learn-javascript = Learn JavaScript
menu-learn-learn-javascript-dynamic-scripting-with-javascript-module = Dynamic scripting with JavaScript module
menu-tools = Tools
menu-tools-panel-title = Discover our tools
menu-tools-0-playground = Playground
menu-tools-0-http-observatory = HTTP Observatory
menu-tools-1-border-image-generator = Border-image generator
menu-tools-1-border-radius-generator = Border-radius generator
menu-tools-1-box-shadow-generator = Box-shadow generator
menu-tools-1-color-format-converter = Color format converter
menu-tools-1-color-mixer = Color mixer
menu-tools-1-shape-generator = Shape generator
menu-about = About
menu-about-panel-title = Get to know MDN better
menu-about-0-about-mdn = About MDN
menu-about-0-advertise-with-us = Advertise with us
menu-about-1-community = Community
menu-about-1-mdn-on-github = MDN on GitHub
menu-blog = Blog
